-- +goose Up
ALTER TABLE users ADD COLUMN full_name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN email VARCHAR(255) UNIQUE;

-- +goose Down
ALTER TABLE users DROP COLUMN IF EXISTS email;
ALTER TABLE users DROP COLUMN IF EXISTS full_name;
